# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturter', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('seep_changing_box', models.CharField(max_length=30)),
                ('car_body', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('wheel_base', models.CharField(max_length=30)),
                ('trunk', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('car_license', models.DateTimeField(max_length=100)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('mileage', models.CharField(max_length=100)),
                ('market', models.FloatField()),
                ('Register_time', models.DateTimeField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('emission_standard', models.CharField(max_length=100)),
                ('speed_changing_box', models.CharField(max_length=100)),
                ('custom_id', models.CharField(max_length=100)),
                ('discharge', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('address_of_a_car', models.CharField(max_length=100)),
                ('annual_inspection', models.DateTimeField(max_length=50)),
                ('insurance', models.DateTimeField(max_length=50)),
                ('commercial_insuranc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chassis_braking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_mode', models.CharField(max_length=50)),
                ('Power_type', models.CharField(max_length=50)),
                ('Front_suspension_type', models.CharField(max_length=50)),
                ('Rear_suspeusion_type', models.CharField(max_length=50)),
                ('front_brake_type', models.CharField(max_length=50)),
                ('rear_brake_type', models.CharField(max_length=50)),
                ('parking_brake_type', models.CharField(max_length=50)),
                ('front_tire_type', models.CharField(max_length=50)),
                ('rear_tire_type', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail_detail.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Engine_parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=100)),
                ('discharge', models.FloatField()),
                ('intake_type', models.CharField(max_length=100)),
                ('air_cyinder', models.CharField(max_length=50)),
                ('max_horsepower', models.CharField(max_length=50)),
                ('torque', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('Alimentation', models.CharField(max_length=50)),
                ('emission_standard', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail_detail.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail_detail.Owner'),
        ),
        migrations.AddField(
            model_name='basic_parameter',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail_detail.Car'),
        ),
    ]
